#!/bin/bash

#
# Run yarn install when checkout a branch if yarn.lock has changed
#

prevHEAD=$1                                                                      
newHEAD=$2   
checkoutMode=$3 # 1: branches, 0: files   

check_run() {
    # it works only if I'm switching branch
    if [[ $checkoutMode == 1 ]]; then
        changed_files="$(git diff --name-only $prevHEAD..$newHEAD)"
	    echo "$changed_files" | grep --quiet "$1" && eval "$2"
    fi
}

# run yarn install when dependencies have changed
check_run yarn.lock "yarn cache clean && yarn install"


exit 0;
