#!/bin/bash

#
# Run yarn install when merging changes from another branch if yarn.lock has changed
#

check_run() {
    changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"
	echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

# run yarn install when dependencies have changed
check_run yarn.lock "yarn cache clean && yarn install"