#!/bin/bash

#
# Run yarn install when checkout a branch if yarn.lock has changed
#

prevHEAD=$1                                                                      
newHEAD=$2   

check_run() {
    changed_files="$(git diff --name-only $prevHEAD..$newHEAD)"
	echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

# run yarn install when dependencies have changed
check_run yarn.lock "yarn cache list && yarn install"