#!/bin/bash

#
# Ensure everything is fine before committing stuff
#

# Test if you can actually execute the provider
PROVIDER_COMMAND=$(git config --get secrets.providers)
if [ ! -z "$PROVIDER_COMMAND" ]; then
    # no need to print the output
    $($PROVIDER_COMMAND > /dev/null 2>&1)
    RETURN_CODE=$?
    if [ $RETURN_CODE -ne 0 ]; then
        echo "Provider command:"
        echo "$PROVIDER_COMMAND"
        echo "The above command failed execution. Nothing has been commited."
        echo "Please check your .git/config file, secrets.providers section."
        # whatever value != 0
        exit $RETURN_CODE
    fi
fi

git secrets --pre_commit_hook -- "$@"

#
# Double-check to prevent unwanted commit on master/main branch
#

branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "master" ] || [ "$branch" = "main" ]; then
  printf "\n\e[33mYou are about to commit on %s branch.\e[0m\n\n" "$branch"
  read -rp "Write 'yes' to continue, enter to abort: " response < /dev/tty
  ##response=${response,,} # tolower
  if [[ ! $response =~ ^(y|yes) ]]; then
    echo "Commit aborted."
    exit 1
  fi
fi
